export const CATEGORIES = [
  { id: 1, name: 'Điện thoại', icon: '📱', slug: 'dien-thoai' },
  { id: 2, name: 'Laptop', icon: '💻', slug: 'laptop' },
  { id: 3, name: 'Máy tính bảng', icon: '📲', slug: 'may-tinh-bang' },
  { id: 4, name: 'Âm thanh', icon: '🎧', slug: 'am-thanh' },
  { id: 5, name: 'Máy ảnh', icon: '📷', slug: 'may-anh' },
  { id: 6, name: 'Đồng hồ', icon: '⌚', slug: 'dong-ho' },
  { id: 7, name: 'Phụ kiện', icon: '🔌', slug: 'phu-kien' },
  { id: 8, name: 'Gia dụng', icon: '🏠', slug: 'gia-dung' },
]

export const CATEGORY_TREE = [
  {
    id: 1, name: 'Điện thoại & Máy tính bảng', slug: 'dien-thoai',
    icon: '📱',
    children: [
      { id: 11, name: 'Điện thoại iPhone', slug: 'iphone' },
      { id: 12, name: 'Điện thoại Samsung', slug: 'samsung' },
      { id: 13, name: 'Điện thoại Xiaomi', slug: 'xiaomi' },
      { id: 14, name: 'Máy tính bảng iPad', slug: 'ipad' },
    ],
  },
  {
    id: 2, name: 'Laptop & Máy tính', slug: 'laptop',
    icon: '💻',
    children: [
      { id: 21, name: 'MacBook', slug: 'macbook' },
      { id: 22, name: 'Laptop Windows', slug: 'laptop-windows' },
      { id: 23, name: 'PC Bàn', slug: 'pc' },
    ],
  },
  {
    id: 3, name: 'Âm thanh', slug: 'am-thanh',
    icon: '🎧',
    children: [
      { id: 31, name: 'Tai nghe', slug: 'tai-nghe' },
      { id: 32, name: 'Loa bluetooth', slug: 'loa' },
    ],
  },
  {
    id: 4, name: 'Máy ảnh & Quay phim', slug: 'may-anh',
    icon: '📷',
    children: [
      { id: 41, name: 'Máy ảnh DSLR', slug: 'dslr' },
      { id: 42, name: 'Máy ảnh mirrorless', slug: 'mirrorless' },
    ],
  },
  {
    id: 5, name: 'Đồng hồ & Wearable', slug: 'dong-ho',
    icon: '⌚',
    children: [
      { id: 51, name: 'Apple Watch', slug: 'apple-watch' },
      { id: 52, name: 'Đồng hồ thông minh', slug: 'smartwatch' },
    ],
  },
  {
    id: 6, name: 'Gia dụng & Nhà bếp', slug: 'gia-dung',
    icon: '🏠',
    children: [
      { id: 61, name: 'Robot hút bụi', slug: 'robot-hut-bui' },
      { id: 62, name: 'Nồi chiên không dầu', slug: 'noi-chien' },
    ],
  },
]

export const FEATURED_PRODUCTS = [
  { id: 1, name: 'iPhone 15 Pro Max 256GB', price: 28990000, originalPrice: 32990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=iPhone+15', category: 'Điện thoại', badge: 'HOT' },
  { id: 2, name: 'Samsung Galaxy S24 Ultra', price: 25990000, originalPrice: 29990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Samsung+S24', category: 'Điện thoại', badge: 'SALE' },
  { id: 3, name: 'MacBook Air M3 13 inch', price: 27990000, originalPrice: 30990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=MacBook+M3', category: 'Laptop', badge: 'MỚI' },
  { id: 4, name: 'iPad Pro M4 11 inch', price: 19990000, originalPrice: 22990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=iPad+Pro', category: 'Máy tính bảng', badge: '' },
  { id: 5, name: 'Sony WH-1000XM5', price: 6490000, originalPrice: 8490000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Sony+XM5', category: 'Âm thanh', badge: 'SALE' },
  { id: 6, name: 'Apple Watch Series 9', price: 9990000, originalPrice: 11990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=AWatch+S9', category: 'Đồng hồ', badge: '' },
  { id: 7, name: 'Canon EOS R50', price: 17990000, originalPrice: 19990000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Canon+R50', category: 'Máy ảnh', badge: '' },
  { id: 8, name: 'Xiaomi Robot Vacuum S10', price: 3990000, originalPrice: 5490000, image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Xiaomi+Vacuum', category: 'Gia dụng', badge: 'HOT' },
]

export interface Product {
  id: number
  name: string
  slug: string
  price: number
  originalPrice: number
  image: string
  category: string
  categorySlug: string
  badge: string
  rating: number
  reviewCount: number
  inStock: boolean
  variantId?: number
}

export const ALL_PRODUCTS: Product[] = [
  {
    id: 101,
    name: 'iPhone 15 Pro Max 256GB Titan Đen',
    slug: 'iphone-15-pro-max-256gb',
    price: 28990000,
    originalPrice: 32990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=iPhone+15+Pro',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'HOT',
    rating: 4.9,
    reviewCount: 482,
    inStock: true,
  },
  {
    id: 102,
    name: 'Samsung Galaxy S24 Ultra 512GB',
    slug: 'samsung-galaxy-s24-ultra-512gb',
    price: 25990000,
    originalPrice: 29990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=S24+Ultra',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'SALE',
    rating: 4.8,
    reviewCount: 315,
    inStock: true,
  },
  {
    id: 103,
    name: 'Xiaomi 14 Ultra 512GB',
    slug: 'xiaomi-14-ultra-512gb',
    price: 22990000,
    originalPrice: 24990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Xiaomi+14',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'MỚI',
    rating: 4.7,
    reviewCount: 128,
    inStock: true,
  },
  {
    id: 104,
    name: 'OPPO Find X7 Pro 256GB',
    slug: 'oppo-find-x7-pro-256gb',
    price: 18990000,
    originalPrice: 21990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=OPPO+X7',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'SALE',
    rating: 4.5,
    reviewCount: 87,
    inStock: true,
  },
  {
    id: 105,
    name: 'MacBook Air M3 13 inch 16GB 256GB',
    slug: 'macbook-air-m3-13-inch',
    price: 27990000,
    originalPrice: 30990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=MacBook+M3',
    category: 'Laptop',
    categorySlug: 'laptop',
    badge: 'MỚI',
    rating: 4.9,
    reviewCount: 256,
    inStock: true,
  },
  {
    id: 106,
    name: 'MacBook Pro M3 Pro 14 inch 18GB 512GB',
    slug: 'macbook-pro-m3-pro-14-inch',
    price: 49990000,
    originalPrice: 54990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=MBP+M3+Pro',
    category: 'Laptop',
    categorySlug: 'laptop',
    badge: '',
    rating: 4.9,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: 107,
    name: 'Dell XPS 13 Plus Core i7 32GB 1TB',
    slug: 'dell-xps-13-plus-i7',
    price: 35990000,
    originalPrice: 39990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Dell+XPS+13',
    category: 'Laptop',
    categorySlug: 'laptop',
    badge: 'SALE',
    rating: 4.6,
    reviewCount: 143,
    inStock: false,
  },
  {
    id: 108,
    name: 'Asus ROG Zephyrus G14 RTX 4060 16GB',
    slug: 'asus-rog-zephyrus-g14',
    price: 32990000,
    originalPrice: 35990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=ROG+G14',
    category: 'Laptop',
    categorySlug: 'laptop',
    badge: 'HOT',
    rating: 4.7,
    reviewCount: 211,
    inStock: true,
  },
  {
    id: 109,
    name: 'iPad Pro M4 11 inch 256GB WiFi',
    slug: 'ipad-pro-m4-11-inch-256gb',
    price: 19990000,
    originalPrice: 22990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=iPad+Pro+M4',
    category: 'Máy tính bảng',
    categorySlug: 'may-tinh-bang',
    badge: 'MỚI',
    rating: 4.8,
    reviewCount: 174,
    inStock: true,
  },
  {
    id: 110,
    name: 'Samsung Galaxy Tab S9 Ultra 256GB',
    slug: 'samsung-galaxy-tab-s9-ultra',
    price: 23990000,
    originalPrice: 26990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Tab+S9+Ultra',
    category: 'Máy tính bảng',
    categorySlug: 'may-tinh-bang',
    badge: 'SALE',
    rating: 4.6,
    reviewCount: 92,
    inStock: true,
  },
  {
    id: 111,
    name: 'Sony WH-1000XM5 Chống ồn Không dây',
    slug: 'sony-wh-1000xm5',
    price: 6490000,
    originalPrice: 8490000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Sony+XM5',
    category: 'Âm thanh',
    categorySlug: 'am-thanh',
    badge: 'SALE',
    rating: 4.9,
    reviewCount: 438,
    inStock: true,
  },
  {
    id: 112,
    name: 'AirPods Pro 2 USB-C Chống ồn',
    slug: 'airpods-pro-2-usbc',
    price: 5990000,
    originalPrice: 6990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=AirPods+Pro+2',
    category: 'Âm thanh',
    categorySlug: 'am-thanh',
    badge: 'HOT',
    rating: 4.8,
    reviewCount: 367,
    inStock: true,
  },
  {
    id: 113,
    name: 'JBL Charge 5 Loa Bluetooth Chống nước',
    slug: 'jbl-charge-5',
    price: 2990000,
    originalPrice: 3490000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=JBL+Charge+5',
    category: 'Âm thanh',
    categorySlug: 'am-thanh',
    badge: '',
    rating: 4.5,
    reviewCount: 203,
    inStock: true,
  },
  {
    id: 114,
    name: 'Canon EOS R50 Kit 18-45mm',
    slug: 'canon-eos-r50-kit',
    price: 17990000,
    originalPrice: 19990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Canon+R50',
    category: 'Máy ảnh',
    categorySlug: 'may-anh',
    badge: '',
    rating: 4.7,
    reviewCount: 115,
    inStock: true,
  },
  {
    id: 115,
    name: 'Sony Alpha A7 IV Body Mirrorless',
    slug: 'sony-alpha-a7-iv-body',
    price: 54990000,
    originalPrice: 59990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Sony+A7+IV',
    category: 'Máy ảnh',
    categorySlug: 'may-anh',
    badge: 'SALE',
    rating: 4.9,
    reviewCount: 78,
    inStock: false,
  },
  {
    id: 116,
    name: 'Apple Watch Series 9 41mm GPS',
    slug: 'apple-watch-series-9-41mm',
    price: 9990000,
    originalPrice: 11990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=AWatch+S9',
    category: 'Đồng hồ',
    categorySlug: 'dong-ho',
    badge: '',
    rating: 4.8,
    reviewCount: 289,
    inStock: true,
  },
  {
    id: 117,
    name: 'Samsung Galaxy Watch 6 Classic 47mm',
    slug: 'samsung-galaxy-watch-6-classic-47mm',
    price: 7990000,
    originalPrice: 9490000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=GWatch+6',
    category: 'Đồng hồ',
    categorySlug: 'dong-ho',
    badge: 'SALE',
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
  },
  {
    id: 118,
    name: 'Cáp sạc USB-C to Lightning 2m MFi',
    slug: 'cap-sac-usbc-lightning-2m-mfi',
    price: 390000,
    originalPrice: 590000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Cable+MFi',
    category: 'Phụ kiện',
    categorySlug: 'phu-kien',
    badge: 'SALE',
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
  },
  {
    id: 119,
    name: 'Ốp lưng MagSafe iPhone 15 Pro Silicone',
    slug: 'op-lung-magsafe-iphone-15-pro-silicone',
    price: 790000,
    originalPrice: 990000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Case+MagSafe',
    category: 'Phụ kiện',
    categorySlug: 'phu-kien',
    badge: '',
    rating: 4.4,
    reviewCount: 187,
    inStock: true,
  },
  {
    id: 120,
    name: 'Xiaomi Robot Vacuum S10+ Hút Lau 2 trong 1',
    slug: 'xiaomi-robot-vacuum-s10-plus',
    price: 5490000,
    originalPrice: 7490000,
    image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Xiaomi+S10+',
    category: 'Gia dụng',
    categorySlug: 'gia-dung',
    badge: 'HOT',
    rating: 4.6,
    reviewCount: 241,
    inStock: true,
  },
]

export interface ProductDetail extends Product {
  description: string
  specs: { label: string; value: string }[]
  images: string[]
  variants: {
    sizes: string[]
    colors: { name: string; hex: string }[]
  }
}

export const PRODUCT_DETAILS: Record<string, ProductDetail> = {
  'iphone-15-pro-max': {
    id: 101,
    name: 'iPhone 15 Pro Max 256GB Titan Đen',
    slug: 'iphone-15-pro-max',
    price: 28990000,
    originalPrice: 32990000,
    image: 'https://placehold.co/600x600/3762cc/ffffff?text=iPhone+15+Pro',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'HOT',
    rating: 4.9,
    reviewCount: 482,
    inStock: true,
    description: 'iPhone 15 Pro Max là chiếc điện thoại cao cấp nhất của Apple năm 2023, được trang bị chip A17 Pro mạnh mẽ, khung Titan siêu bền và hệ thống camera chuyên nghiệp với ống kính tele 5x. Màn hình Super Retina XDR 6.7 inch với công nghệ ProMotion 120Hz mang lại trải nghiệm hiển thị tuyệt vời. Thiết kế mỏng nhẹ với chất liệu Titan cao cấp giúp máy vừa sang trọng vừa bền bỉ. Cổng USB-C hỗ trợ tốc độ truyền dữ liệu lên đến 3.1 Gbps và sạc nhanh.',
    specs: [
      { label: 'Màn hình', value: '6.7 inch Super Retina XDR, ProMotion 120Hz, OLED' },
      { label: 'CPU', value: 'Apple A17 Pro 3nm, 6 nhân' },
      { label: 'RAM', value: '8 GB' },
      { label: 'Bộ nhớ trong', value: '256 GB' },
      { label: 'Camera sau', value: '48MP (chính) + 12MP (góc siêu rộng) + 12MP (tele 5x)' },
      { label: 'Camera trước', value: '12MP TrueDepth' },
      { label: 'Pin', value: '4.422 mAh, sạc nhanh 27W, sạc không dây MagSafe 15W' },
      { label: 'Hệ điều hành', value: 'iOS 17' },
      { label: 'Kết nối', value: '5G, Wi-Fi 6E, Bluetooth 5.3, USB-C 3.1 Gen 2' },
      { label: 'Kích thước', value: '159.9 x 76.7 x 8.25 mm' },
      { label: 'Trọng lượng', value: '221 g' },
      { label: 'Màu sắc', value: 'Titan Đen, Titan Trắng, Titan Xanh, Titan Tự nhiên' },
    ],
    images: [
      'https://placehold.co/600x600/3762cc/ffffff?text=iPhone+15+Pro',
      'https://placehold.co/600x600/1c3b71/ffffff?text=Side+View',
      'https://placehold.co/600x600/f5821f/ffffff?text=Back+View',
    ],
    variants: {
      sizes: ['256GB', '512GB', '1TB'],
      colors: [
        { name: 'Titan Đen', hex: '#3d3d3d' },
        { name: 'Titan Trắng', hex: '#e8e4dc' },
        { name: 'Titan Xanh', hex: '#4a6fa5' },
        { name: 'Titan Tự nhiên', hex: '#c9b99a' },
      ],
    },
  },
  'macbook-air-m3': {
    id: 105,
    name: 'MacBook Air M3 13 inch 16GB 256GB',
    slug: 'macbook-air-m3',
    price: 27990000,
    originalPrice: 30990000,
    image: 'https://placehold.co/600x600/2d2d2d/ffffff?text=MacBook+Air+M3',
    category: 'Laptop',
    categorySlug: 'laptop',
    badge: 'MỚI',
    rating: 4.9,
    reviewCount: 256,
    inStock: true,
    description: 'MacBook Air M3 là laptop mỏng nhẹ, hiệu năng cao nhất trong phân khúc của Apple. Được trang bị chip M3 thế hệ mới nhất với kiến trúc 3nm, mang lại hiệu suất vượt trội so với thế hệ trước đến 60%. Màn hình Liquid Retina 13.6 inch sắc nét với độ phân giải 2560x1664px, hỗ trợ tới 1 tỷ màu sắc. Thời lượng pin lên tới 18 giờ sử dụng liên tục. Thiết kế không quạt giúp máy hoạt động hoàn toàn im lặng.',
    specs: [
      { label: 'Màn hình', value: '13.6 inch Liquid Retina, 2560x1664px, 224 PPI' },
      { label: 'CPU', value: 'Apple M3, 8 nhân CPU (4P + 4E)' },
      { label: 'GPU', value: '10 nhân GPU tích hợp' },
      { label: 'RAM', value: '16 GB Unified Memory' },
      { label: 'Bộ nhớ', value: '256 GB SSD NVMe' },
      { label: 'Pin', value: '52.6 Wh, sạc 30W USB-C, thời lượng 18 giờ' },
      { label: 'Hệ điều hành', value: 'macOS Sonoma' },
      { label: 'Kết nối', value: 'Wi-Fi 6E, Bluetooth 5.3, 2x Thunderbolt/USB 4, MagSafe 3' },
      { label: 'Camera', value: '1080p FaceTime HD' },
      { label: 'Kích thước', value: '304.1 x 215 x 11.5 mm' },
      { label: 'Trọng lượng', value: '1.24 kg' },
      { label: 'Màu sắc', value: 'Midnight, Starlight, Space Gray, Silver' },
    ],
    images: [
      'https://placehold.co/600x600/2d2d2d/ffffff?text=MacBook+Air+M3',
      'https://placehold.co/600x600/3762cc/ffffff?text=Side+View',
      'https://placehold.co/600x600/888888/ffffff?text=Keyboard',
    ],
    variants: {
      sizes: ['8GB/256GB', '16GB/256GB', '16GB/512GB', '24GB/2TB'],
      colors: [
        { name: 'Midnight', hex: '#2c2c2e' },
        { name: 'Starlight', hex: '#e8e4dc' },
        { name: 'Space Gray', hex: '#86868b' },
        { name: 'Silver', hex: '#f5f5f7' },
      ],
    },
  },
  'samsung-s24-ultra': {
    id: 102,
    name: 'Samsung Galaxy S24 Ultra 512GB',
    slug: 'samsung-s24-ultra',
    price: 25990000,
    originalPrice: 29990000,
    image: 'https://placehold.co/600x600/1a1a2e/ffffff?text=S24+Ultra',
    category: 'Điện thoại',
    categorySlug: 'dien-thoai',
    badge: 'SALE',
    rating: 4.8,
    reviewCount: 315,
    inStock: true,
    description: 'Samsung Galaxy S24 Ultra là flagship cao cấp nhất của Samsung với bút S Pen tích hợp, chip Snapdragon 8 Gen 3 mạnh mẽ và hệ thống camera zoom 200MP. Màn hình Dynamic AMOLED 2X 6.8 inch với độ sáng 2600 nits và tần số quét thích ứng 1-120Hz. Galaxy AI mang đến nhiều tính năng AI thông minh như dịch thuật trực tiếp, tóm tắt cuộc gọi và chỉnh sửa ảnh thông minh.',
    specs: [
      { label: 'Màn hình', value: '6.8 inch Dynamic AMOLED 2X, 2600 nits, 120Hz' },
      { label: 'CPU', value: 'Snapdragon 8 Gen 3 for Galaxy, 4nm' },
      { label: 'RAM', value: '12 GB' },
      { label: 'Bộ nhớ trong', value: '512 GB UFS 4.0' },
      { label: 'Camera sau', value: '200MP (chính) + 12MP (góc siêu rộng) + 10MP (tele 3x) + 50MP (tele 5x)' },
      { label: 'Camera trước', value: '12MP' },
      { label: 'Pin', value: '5.000 mAh, sạc nhanh 45W, sạc không dây 15W' },
      { label: 'Hệ điều hành', value: 'Android 14, One UI 6.1' },
      { label: 'Kết nối', value: '5G, Wi-Fi 7, Bluetooth 5.3, USB-C 3.2 Gen 2' },
      { label: 'Bút S Pen', value: 'Tích hợp, độ trễ 2.8ms' },
      { label: 'Kích thước', value: '162.3 x 79 x 8.6 mm' },
      { label: 'Trọng lượng', value: '232 g' },
    ],
    images: [
      'https://placehold.co/600x600/1a1a2e/ffffff?text=S24+Ultra',
      'https://placehold.co/600x600/c0a060/ffffff?text=S+Pen+View',
      'https://placehold.co/600x600/4a4a6a/ffffff?text=Camera+View',
    ],
    variants: {
      sizes: ['256GB', '512GB', '1TB'],
      colors: [
        { name: 'Titanium Black', hex: '#2c2c2e' },
        { name: 'Titanium Gray', hex: '#86868b' },
        { name: 'Titanium Violet', hex: '#7b6fa0' },
        { name: 'Titanium Yellow', hex: '#d4b45a' },
      ],
    },
  },
  'sony-xm5': {
    id: 111,
    name: 'Sony WH-1000XM5 Chống ồn Không dây',
    slug: 'sony-xm5',
    price: 6490000,
    originalPrice: 8490000,
    image: 'https://placehold.co/600x600/1a1a1a/ffffff?text=Sony+XM5',
    category: 'Âm thanh',
    categorySlug: 'am-thanh',
    badge: 'SALE',
    rating: 4.9,
    reviewCount: 438,
    inStock: true,
    description: 'Sony WH-1000XM5 là tai nghe chống ồn chủ động hàng đầu thế giới với 8 micro và 2 bộ xử lý âm thanh QN1e và V1. Công nghệ chống ồn Adaptive Sound Control tự động điều chỉnh theo môi trường xung quanh. Thời lượng pin 30 giờ với chế độ chống ồn bật, sạc nhanh 3 phút cho 3 giờ nghe nhạc. Driver 30mm tùy chỉnh mang lại âm thanh Hi-Res Audio chuẩn LDAC chất lượng cao.',
    specs: [
      { label: 'Driver', value: '30mm, Dynamic (neodymium)' },
      { label: 'Đáp tần', value: '4Hz - 40kHz (JEITA)' },
      { label: 'Chống ồn', value: 'Chủ động (ANC), 8 micro, chip QN1e + V1' },
      { label: 'Kết nối', value: 'Bluetooth 5.2, multipoint 2 thiết bị, NFC' },
      { label: 'Codec', value: 'SBC, AAC, LDAC (Hi-Res Audio)' },
      { label: 'Pin', value: '30 giờ (ANC bật), 40 giờ (ANC tắt)' },
      { label: 'Sạc nhanh', value: '3 phút sạc = 3 giờ nghe' },
      { label: 'Trọng lượng', value: '250 g' },
      { label: 'Micro', value: '8 micro (4 phản hồi, 4 chuyển tiếp)' },
      { label: 'Kết nối có dây', value: '3.5mm jack âm thanh' },
      { label: 'Tương thích', value: 'Android, iOS, Windows, Mac' },
    ],
    images: [
      'https://placehold.co/600x600/1a1a1a/ffffff?text=Sony+XM5',
      'https://placehold.co/600x600/3762cc/ffffff?text=Side+View',
      'https://placehold.co/600x600/c0c0c0/333333?text=Silver+View',
    ],
    variants: {
      sizes: ['One Size'],
      colors: [
        { name: 'Đen', hex: '#1a1a1a' },
        { name: 'Trắng Kem', hex: '#e8e4d8' },
      ],
    },
  },
}

export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled'

export interface OrderItem {
  productId: number
  name: string
  image: string
  price: number
  quantity: number
  variant: string
}

export interface Order {
  id: string
  orderNumber: string
  status: OrderStatus
  createdAt: string
  updatedAt: string
  items: OrderItem[]
  subtotal: number
  shipping: number
  total: number
  contactName: string
  contactEmail: string
  contactPhone: string
  address: string
  timeline: {
    status: OrderStatus
    label: string
    description: string
    timestamp: string
    completed: boolean
  }[]
}

export const MOCK_ORDERS: Order[] = [
  {
    id: 'mock-order-1',
    orderNumber: 'DH-20240315-001',
    status: 'delivered',
    createdAt: '2024-03-15T09:00:00.000Z',
    updatedAt: '2024-03-19T14:30:00.000Z',
    items: [
      {
        productId: 101,
        name: 'iPhone 15 Pro Max 256GB Titan Đen',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=iPhone+15+Pro',
        price: 28990000,
        quantity: 1,
        variant: '256GB - Titan Đen',
      },
      {
        productId: 119,
        name: 'Ốp lưng MagSafe iPhone 15 Pro Silicone',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Case+MagSafe',
        price: 790000,
        quantity: 1,
        variant: 'Xanh Navy',
      },
    ],
    subtotal: 29780000,
    shipping: 0,
    total: 29780000,
    contactName: 'Nguyễn Văn An',
    contactEmail: 'nguyenvanan@gmail.com',
    contactPhone: '0901234567',
    address: '123 Đường Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    timeline: [
      {
        status: 'pending',
        label: 'Đặt hàng',
        description: 'Đơn hàng đã được đặt thành công',
        timestamp: '2024-03-15T09:00:00.000Z',
        completed: true,
      },
      {
        status: 'processing',
        label: 'Xác nhận',
        description: 'Đơn hàng đã được xác nhận và đang chuẩn bị',
        timestamp: '2024-03-15T11:30:00.000Z',
        completed: true,
      },
      {
        status: 'shipped',
        label: 'Đang giao',
        description: 'Đơn hàng đang được vận chuyển đến địa chỉ của bạn',
        timestamp: '2024-03-17T08:00:00.000Z',
        completed: true,
      },
      {
        status: 'delivered',
        label: 'Đã nhận hàng',
        description: 'Đơn hàng đã được giao thành công',
        timestamp: '2024-03-19T14:30:00.000Z',
        completed: true,
      },
    ],
  },
  {
    id: 'mock-order-2',
    orderNumber: 'DH-20240401-042',
    status: 'shipped',
    createdAt: '2024-04-01T14:20:00.000Z',
    updatedAt: '2024-04-03T07:45:00.000Z',
    items: [
      {
        productId: 105,
        name: 'MacBook Air M3 13 inch 16GB 256GB',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=MacBook+M3',
        price: 27990000,
        quantity: 1,
        variant: '16GB / 256GB - Midnight',
      },
    ],
    subtotal: 27990000,
    shipping: 30000,
    total: 28020000,
    contactName: 'Trần Thị Bích',
    contactEmail: 'tranthibich@outlook.com',
    contactPhone: '0912345678',
    address: '456 Đường Nguyễn Huệ, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh',
    timeline: [
      {
        status: 'pending',
        label: 'Đặt hàng',
        description: 'Đơn hàng đã được đặt thành công',
        timestamp: '2024-04-01T14:20:00.000Z',
        completed: true,
      },
      {
        status: 'processing',
        label: 'Xác nhận',
        description: 'Đơn hàng đã được xác nhận và đang chuẩn bị',
        timestamp: '2024-04-01T16:00:00.000Z',
        completed: true,
      },
      {
        status: 'shipped',
        label: 'Đang giao',
        description: 'Đơn hàng đang được vận chuyển đến địa chỉ của bạn',
        timestamp: '2024-04-03T07:45:00.000Z',
        completed: true,
      },
      {
        status: 'delivered',
        label: 'Đã nhận hàng',
        description: 'Dự kiến giao ngày 05/04/2024',
        timestamp: '',
        completed: false,
      },
    ],
  },
  {
    id: 'mock-order-3',
    orderNumber: 'DH-20240404-118',
    status: 'processing',
    createdAt: '2024-04-04T10:05:00.000Z',
    updatedAt: '2024-04-04T11:00:00.000Z',
    items: [
      {
        productId: 111,
        name: 'Sony WH-1000XM5 Chống ồn Không dây',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Sony+XM5',
        price: 6490000,
        quantity: 1,
        variant: 'Đen',
      },
      {
        productId: 113,
        name: 'JBL Charge 5 Loa Bluetooth Chống nước',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=JBL+Charge+5',
        price: 2990000,
        quantity: 1,
        variant: 'Đỏ',
      },
      {
        productId: 118,
        name: 'Cáp sạc USB-C to Lightning 2m MFi',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=Cable+MFi',
        price: 390000,
        quantity: 2,
        variant: 'Trắng',
      },
    ],
    subtotal: 10260000,
    shipping: 30000,
    total: 10290000,
    contactName: 'Lê Minh Tuấn',
    contactEmail: 'leminhtuandev@gmail.com',
    contactPhone: '0987654321',
    address: '78 Đường Hoàng Diệu, Phường 12, Quận 4, TP. Hồ Chí Minh',
    timeline: [
      {
        status: 'pending',
        label: 'Đặt hàng',
        description: 'Đơn hàng đã được đặt thành công',
        timestamp: '2024-04-04T10:05:00.000Z',
        completed: true,
      },
      {
        status: 'processing',
        label: 'Xác nhận',
        description: 'Đơn hàng đang được xác nhận và chuẩn bị hàng',
        timestamp: '2024-04-04T11:00:00.000Z',
        completed: true,
      },
      {
        status: 'shipped',
        label: 'Đang giao',
        description: 'Đơn hàng sẽ sớm được vận chuyển',
        timestamp: '',
        completed: false,
      },
      {
        status: 'delivered',
        label: 'Đã nhận hàng',
        description: '',
        timestamp: '',
        completed: false,
      },
    ],
  },
  {
    id: 'mock-order-4',
    orderNumber: 'DH-20240320-077',
    status: 'cancelled',
    createdAt: '2024-03-20T16:30:00.000Z',
    updatedAt: '2024-03-21T09:00:00.000Z',
    items: [
      {
        productId: 116,
        name: 'Apple Watch Series 9 41mm GPS',
        image: 'https://placehold.co/300x300/e2e8f0/64748b?text=AWatch+S9',
        price: 9990000,
        quantity: 1,
        variant: '41mm - Dây Midnight',
      },
    ],
    subtotal: 9990000,
    shipping: 0,
    total: 9990000,
    contactName: 'Phạm Thị Hương',
    contactEmail: 'phamhuong2024@yahoo.com',
    contactPhone: '0938765432',
    address: '22 Đường Đinh Tiên Hoàng, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh',
    timeline: [
      {
        status: 'pending',
        label: 'Đặt hàng',
        description: 'Đơn hàng đã được đặt thành công',
        timestamp: '2024-03-20T16:30:00.000Z',
        completed: true,
      },
      {
        status: 'cancelled',
        label: 'Xác nhận',
        description: 'Đơn hàng đã bị huỷ theo yêu cầu của khách hàng',
        timestamp: '2024-03-21T09:00:00.000Z',
        completed: true,
      },
      {
        status: 'shipped',
        label: 'Đang giao',
        description: '',
        timestamp: '',
        completed: false,
      },
      {
        status: 'delivered',
        label: 'Đã nhận hàng',
        description: '',
        timestamp: '',
        completed: false,
      },
    ],
  },
]

export const SEARCH_SUGGESTIONS = [
  { id: 1, name: 'iPhone 15 Pro Max', category: 'Điện thoại', slug: 'iphone-15-pro-max' },
  { id: 2, name: 'iPhone 15 Pro', category: 'Điện thoại', slug: 'iphone-15-pro' },
  { id: 3, name: 'iPhone 14', category: 'Điện thoại', slug: 'iphone-14' },
  { id: 4, name: 'Samsung Galaxy S24 Ultra', category: 'Điện thoại', slug: 'samsung-s24-ultra' },
  { id: 5, name: 'Samsung Galaxy A55', category: 'Điện thoại', slug: 'samsung-a55' },
  { id: 6, name: 'MacBook Air M3', category: 'Laptop', slug: 'macbook-air-m3' },
  { id: 7, name: 'MacBook Pro M3', category: 'Laptop', slug: 'macbook-pro-m3' },
  { id: 8, name: 'Laptop Dell XPS 13', category: 'Laptop', slug: 'dell-xps-13' },
  { id: 9, name: 'iPad Pro M4', category: 'Máy tính bảng', slug: 'ipad-pro-m4' },
  { id: 10, name: 'iPad Air M2', category: 'Máy tính bảng', slug: 'ipad-air-m2' },
  { id: 11, name: 'Sony WH-1000XM5', category: 'Âm thanh', slug: 'sony-xm5' },
  { id: 12, name: 'AirPods Pro 2', category: 'Âm thanh', slug: 'airpods-pro-2' },
  { id: 13, name: 'Apple Watch Series 9', category: 'Đồng hồ', slug: 'apple-watch-s9' },
  { id: 14, name: 'Canon EOS R50', category: 'Máy ảnh', slug: 'canon-r50' },
  { id: 15, name: 'Xiaomi Robot Vacuum S10', category: 'Gia dụng', slug: 'xiaomi-vacuum-s10' },
]
